// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battle.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "battle.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace boids {

namespace {

const ::google_lalune::protobuf::Descriptor* MatchRequest_descriptor_ = NULL;
const ::google_lalune::protobuf::internal::GeneratedMessageReflection*
  MatchRequest_reflection_ = NULL;
const ::google_lalune::protobuf::Descriptor* MatchResponse_descriptor_ = NULL;
const ::google_lalune::protobuf::internal::GeneratedMessageReflection*
  MatchResponse_reflection_ = NULL;
const ::google_lalune::protobuf::EnumDescriptor* MatchResponse_Value_descriptor_ = NULL;
const ::google_lalune::protobuf::Descriptor* CreateGame_descriptor_ = NULL;
const ::google_lalune::protobuf::internal::GeneratedMessageReflection*
  CreateGame_reflection_ = NULL;
const ::google_lalune::protobuf::Descriptor* CreateGameResponse_descriptor_ = NULL;
const ::google_lalune::protobuf::internal::GeneratedMessageReflection*
  CreateGameResponse_reflection_ = NULL;
const ::google_lalune::protobuf::Descriptor* PvPServerRegister_descriptor_ = NULL;
const ::google_lalune::protobuf::internal::GeneratedMessageReflection*
  PvPServerRegister_reflection_ = NULL;
const ::google_lalune::protobuf::Descriptor* PvPServerRegisterResponse_descriptor_ = NULL;
const ::google_lalune::protobuf::internal::GeneratedMessageReflection*
  PvPServerRegisterResponse_reflection_ = NULL;
const ::google_lalune::protobuf::Descriptor* PvPServerHeartBeat_descriptor_ = NULL;
const ::google_lalune::protobuf::internal::GeneratedMessageReflection*
  PvPServerHeartBeat_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_battle_2eproto() {
  protobuf_AddDesc_battle_2eproto();
  const ::google_lalune::protobuf::FileDescriptor* file =
    ::google_lalune::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "battle.proto");
  GOOGLE_CHECK(file != NULL);
  MatchRequest_descriptor_ = file->message_type(0);
  static const int MatchRequest_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatchRequest, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatchRequest, map_name_),
  };
  MatchRequest_reflection_ =
    new ::google_lalune::protobuf::internal::GeneratedMessageReflection(
      MatchRequest_descriptor_,
      MatchRequest::default_instance_,
      MatchRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatchRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatchRequest, _unknown_fields_),
      -1,
      ::google_lalune::protobuf::DescriptorPool::generated_pool(),
      ::google_lalune::protobuf::MessageFactory::generated_factory(),
      sizeof(MatchRequest));
  MatchResponse_descriptor_ = file->message_type(1);
  static const int MatchResponse_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatchResponse, game_uuid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatchResponse, game_server_ip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatchResponse, game_server_port_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatchResponse, ret_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatchResponse, ret_info_),
  };
  MatchResponse_reflection_ =
    new ::google_lalune::protobuf::internal::GeneratedMessageReflection(
      MatchResponse_descriptor_,
      MatchResponse::default_instance_,
      MatchResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatchResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatchResponse, _unknown_fields_),
      -1,
      ::google_lalune::protobuf::DescriptorPool::generated_pool(),
      ::google_lalune::protobuf::MessageFactory::generated_factory(),
      sizeof(MatchResponse));
  MatchResponse_Value_descriptor_ = MatchResponse_descriptor_->enum_type(0);
  CreateGame_descriptor_ = file->message_type(2);
  static const int CreateGame_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateGame, game_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateGame, game_init_data_),
  };
  CreateGame_reflection_ =
    new ::google_lalune::protobuf::internal::GeneratedMessageReflection(
      CreateGame_descriptor_,
      CreateGame::default_instance_,
      CreateGame_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateGame, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateGame, _unknown_fields_),
      -1,
      ::google_lalune::protobuf::DescriptorPool::generated_pool(),
      ::google_lalune::protobuf::MessageFactory::generated_factory(),
      sizeof(CreateGame));
  CreateGameResponse_descriptor_ = file->message_type(3);
  static const int CreateGameResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateGameResponse, game_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateGameResponse, ret_value_),
  };
  CreateGameResponse_reflection_ =
    new ::google_lalune::protobuf::internal::GeneratedMessageReflection(
      CreateGameResponse_descriptor_,
      CreateGameResponse::default_instance_,
      CreateGameResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateGameResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateGameResponse, _unknown_fields_),
      -1,
      ::google_lalune::protobuf::DescriptorPool::generated_pool(),
      ::google_lalune::protobuf::MessageFactory::generated_factory(),
      sizeof(CreateGameResponse));
  PvPServerRegister_descriptor_ = file->message_type(4);
  static const int PvPServerRegister_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerRegister, ip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerRegister, port_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerRegister, region_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerRegister, priority_),
  };
  PvPServerRegister_reflection_ =
    new ::google_lalune::protobuf::internal::GeneratedMessageReflection(
      PvPServerRegister_descriptor_,
      PvPServerRegister::default_instance_,
      PvPServerRegister_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerRegister, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerRegister, _unknown_fields_),
      -1,
      ::google_lalune::protobuf::DescriptorPool::generated_pool(),
      ::google_lalune::protobuf::MessageFactory::generated_factory(),
      sizeof(PvPServerRegister));
  PvPServerRegisterResponse_descriptor_ = file->message_type(5);
  static const int PvPServerRegisterResponse_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerRegisterResponse, ret_value_),
  };
  PvPServerRegisterResponse_reflection_ =
    new ::google_lalune::protobuf::internal::GeneratedMessageReflection(
      PvPServerRegisterResponse_descriptor_,
      PvPServerRegisterResponse::default_instance_,
      PvPServerRegisterResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerRegisterResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerRegisterResponse, _unknown_fields_),
      -1,
      ::google_lalune::protobuf::DescriptorPool::generated_pool(),
      ::google_lalune::protobuf::MessageFactory::generated_factory(),
      sizeof(PvPServerRegisterResponse));
  PvPServerHeartBeat_descriptor_ = file->message_type(6);
  static const int PvPServerHeartBeat_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerHeartBeat, ip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerHeartBeat, port_),
  };
  PvPServerHeartBeat_reflection_ =
    new ::google_lalune::protobuf::internal::GeneratedMessageReflection(
      PvPServerHeartBeat_descriptor_,
      PvPServerHeartBeat::default_instance_,
      PvPServerHeartBeat_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerHeartBeat, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PvPServerHeartBeat, _unknown_fields_),
      -1,
      ::google_lalune::protobuf::DescriptorPool::generated_pool(),
      ::google_lalune::protobuf::MessageFactory::generated_factory(),
      sizeof(PvPServerHeartBeat));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google_lalune::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_battle_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google_lalune::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MatchRequest_descriptor_, &MatchRequest::default_instance());
  ::google_lalune::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MatchResponse_descriptor_, &MatchResponse::default_instance());
  ::google_lalune::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CreateGame_descriptor_, &CreateGame::default_instance());
  ::google_lalune::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CreateGameResponse_descriptor_, &CreateGameResponse::default_instance());
  ::google_lalune::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PvPServerRegister_descriptor_, &PvPServerRegister::default_instance());
  ::google_lalune::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PvPServerRegisterResponse_descriptor_, &PvPServerRegisterResponse::default_instance());
  ::google_lalune::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PvPServerHeartBeat_descriptor_, &PvPServerHeartBeat::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_battle_2eproto() {
  delete MatchRequest::default_instance_;
  delete MatchRequest_reflection_;
  delete MatchResponse::default_instance_;
  delete MatchResponse_reflection_;
  delete CreateGame::default_instance_;
  delete CreateGame_reflection_;
  delete CreateGameResponse::default_instance_;
  delete CreateGameResponse_reflection_;
  delete PvPServerRegister::default_instance_;
  delete PvPServerRegister_reflection_;
  delete PvPServerRegisterResponse::default_instance_;
  delete PvPServerRegisterResponse_reflection_;
  delete PvPServerHeartBeat::default_instance_;
  delete PvPServerHeartBeat_reflection_;
}

void protobuf_AddDesc_battle_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::boids::protobuf_AddDesc_pvp_2eproto();
  ::google_lalune::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014battle.proto\022\005boids\032\tpvp.proto\"1\n\014Matc"
    "hRequest\022\017\n\007user_id\030\001 \002(\t\022\020\n\010map_name\030\002 "
    "\002(\t\"\371\001\n\rMatchResponse\022\021\n\tgame_uuid\030\001 \001(\014"
    "\022\026\n\016game_server_ip\030\003 \001(\t\022\030\n\020game_server_"
    "port\030\004 \001(\r\0226\n\tret_value\030\005 \002(\0162\032.boids.Ma"
    "tchResponse.Value:\007Success\022\020\n\010ret_info\030\006"
    " \001(\t\"Y\n\005Value\022\013\n\007Success\020\000\022\r\n\tNo_Server\020"
    "\001\022\020\n\014MatchTimeout\020\002\022\016\n\nCreateFail\020\003\022\022\n\016I"
    "llegalRequest\020\004\"J\n\nCreateGame\022\017\n\007game_id"
    "\030\001 \002(\014\022+\n\016game_init_data\030\002 \002(\0132\023.boids.G"
    "ameInitData\"8\n\022CreateGameResponse\022\017\n\007gam"
    "e_id\030\001 \002(\014\022\021\n\tret_value\030\002 \002(\005\"O\n\021PvPServ"
    "erRegister\022\n\n\002ip\030\001 \002(\t\022\014\n\004port\030\002 \002(\r\022\016\n\006"
    "region\030\003 \001(\005\022\020\n\010priority\030\004 \001(\005\"1\n\031PvPSer"
    "verRegisterResponse\022\024\n\tret_value\030\001 \002(\005:\001"
    "0\".\n\022PvPServerHeartBeat\022\n\n\002ip\030\001 \002(\t\022\014\n\004p"
    "ort\030\002 \002(\r", 649);
  ::google_lalune::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "battle.proto", &protobuf_RegisterTypes);
  MatchRequest::default_instance_ = new MatchRequest();
  MatchResponse::default_instance_ = new MatchResponse();
  CreateGame::default_instance_ = new CreateGame();
  CreateGameResponse::default_instance_ = new CreateGameResponse();
  PvPServerRegister::default_instance_ = new PvPServerRegister();
  PvPServerRegisterResponse::default_instance_ = new PvPServerRegisterResponse();
  PvPServerHeartBeat::default_instance_ = new PvPServerHeartBeat();
  MatchRequest::default_instance_->InitAsDefaultInstance();
  MatchResponse::default_instance_->InitAsDefaultInstance();
  CreateGame::default_instance_->InitAsDefaultInstance();
  CreateGameResponse::default_instance_->InitAsDefaultInstance();
  PvPServerRegister::default_instance_->InitAsDefaultInstance();
  PvPServerRegisterResponse::default_instance_->InitAsDefaultInstance();
  PvPServerHeartBeat::default_instance_->InitAsDefaultInstance();
  ::google_lalune::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_battle_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_battle_2eproto {
  StaticDescriptorInitializer_battle_2eproto() {
    protobuf_AddDesc_battle_2eproto();
  }
} static_descriptor_initializer_battle_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MatchRequest::kUserIdFieldNumber;
const int MatchRequest::kMapNameFieldNumber;
#endif  // !_MSC_VER

MatchRequest::MatchRequest()
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:boids.MatchRequest)
}

void MatchRequest::InitAsDefaultInstance() {
}

MatchRequest::MatchRequest(const MatchRequest& from)
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:boids.MatchRequest)
}

void MatchRequest::SharedCtor() {
  ::google_lalune::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  user_id_ = const_cast< ::std::string*>(&::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited());
  map_name_ = const_cast< ::std::string*>(&::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MatchRequest::~MatchRequest() {
  // @@protoc_insertion_point(destructor:boids.MatchRequest)
  SharedDtor();
}

void MatchRequest::SharedDtor() {
  if (user_id_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete user_id_;
  }
  if (map_name_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete map_name_;
  }
  if (this != default_instance_) {
  }
}

void MatchRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google_lalune::protobuf::Descriptor* MatchRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MatchRequest_descriptor_;
}

const MatchRequest& MatchRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

MatchRequest* MatchRequest::default_instance_ = NULL;

MatchRequest* MatchRequest::New() const {
  return new MatchRequest;
}

void MatchRequest::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_user_id()) {
      if (user_id_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
        user_id_->clear();
      }
    }
    if (has_map_name()) {
      if (map_name_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
        map_name_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MatchRequest::MergePartialFromCodedStream(
    ::google_lalune::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google_lalune::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:boids.MatchRequest)
  for (;;) {
    ::std::pair< ::google_lalune::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google_lalune::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string user_id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google_lalune::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_user_id()));
          ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->user_id().data(), this->user_id().length(),
            ::google_lalune::protobuf::internal::WireFormat::PARSE,
            "user_id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_map_name;
        break;
      }

      // required string map_name = 2;
      case 2: {
        if (tag == 18) {
         parse_map_name:
          DO_(::google_lalune::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_map_name()));
          ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->map_name().data(), this->map_name().length(),
            ::google_lalune::protobuf::internal::WireFormat::PARSE,
            "map_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google_lalune::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google_lalune::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google_lalune::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:boids.MatchRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:boids.MatchRequest)
  return false;
#undef DO_
}

void MatchRequest::SerializeWithCachedSizes(
    ::google_lalune::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:boids.MatchRequest)
  // required string user_id = 1;
  if (has_user_id()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->user_id().data(), this->user_id().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "user_id");
    ::google_lalune::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->user_id(), output);
  }

  // required string map_name = 2;
  if (has_map_name()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->map_name().data(), this->map_name().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "map_name");
    ::google_lalune::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->map_name(), output);
  }

  if (!unknown_fields().empty()) {
    ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:boids.MatchRequest)
}

::google_lalune::protobuf::uint8* MatchRequest::SerializeWithCachedSizesToArray(
    ::google_lalune::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:boids.MatchRequest)
  // required string user_id = 1;
  if (has_user_id()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->user_id().data(), this->user_id().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "user_id");
    target =
      ::google_lalune::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->user_id(), target);
  }

  // required string map_name = 2;
  if (has_map_name()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->map_name().data(), this->map_name().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "map_name");
    target =
      ::google_lalune::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->map_name(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:boids.MatchRequest)
  return target;
}

int MatchRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string user_id = 1;
    if (has_user_id()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::StringSize(
          this->user_id());
    }

    // required string map_name = 2;
    if (has_map_name()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::StringSize(
          this->map_name());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google_lalune::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MatchRequest::MergeFrom(const ::google_lalune::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MatchRequest* source =
    ::google_lalune::protobuf::internal::dynamic_cast_if_available<const MatchRequest*>(
      &from);
  if (source == NULL) {
    ::google_lalune::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MatchRequest::MergeFrom(const MatchRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
    if (from.has_map_name()) {
      set_map_name(from.map_name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MatchRequest::CopyFrom(const ::google_lalune::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MatchRequest::CopyFrom(const MatchRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MatchRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void MatchRequest::Swap(MatchRequest* other) {
  if (other != this) {
    std::swap(user_id_, other->user_id_);
    std::swap(map_name_, other->map_name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google_lalune::protobuf::Metadata MatchRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google_lalune::protobuf::Metadata metadata;
  metadata.descriptor = MatchRequest_descriptor_;
  metadata.reflection = MatchRequest_reflection_;
  return metadata;
}


// ===================================================================

const ::google_lalune::protobuf::EnumDescriptor* MatchResponse_Value_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MatchResponse_Value_descriptor_;
}
bool MatchResponse_Value_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const MatchResponse_Value MatchResponse::Success;
const MatchResponse_Value MatchResponse::No_Server;
const MatchResponse_Value MatchResponse::MatchTimeout;
const MatchResponse_Value MatchResponse::CreateFail;
const MatchResponse_Value MatchResponse::IllegalRequest;
const MatchResponse_Value MatchResponse::Value_MIN;
const MatchResponse_Value MatchResponse::Value_MAX;
const int MatchResponse::Value_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int MatchResponse::kGameUuidFieldNumber;
const int MatchResponse::kGameServerIpFieldNumber;
const int MatchResponse::kGameServerPortFieldNumber;
const int MatchResponse::kRetValueFieldNumber;
const int MatchResponse::kRetInfoFieldNumber;
#endif  // !_MSC_VER

MatchResponse::MatchResponse()
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:boids.MatchResponse)
}

void MatchResponse::InitAsDefaultInstance() {
}

MatchResponse::MatchResponse(const MatchResponse& from)
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:boids.MatchResponse)
}

void MatchResponse::SharedCtor() {
  ::google_lalune::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  game_uuid_ = const_cast< ::std::string*>(&::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited());
  game_server_ip_ = const_cast< ::std::string*>(&::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited());
  game_server_port_ = 0u;
  ret_value_ = 0;
  ret_info_ = const_cast< ::std::string*>(&::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MatchResponse::~MatchResponse() {
  // @@protoc_insertion_point(destructor:boids.MatchResponse)
  SharedDtor();
}

void MatchResponse::SharedDtor() {
  if (game_uuid_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete game_uuid_;
  }
  if (game_server_ip_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete game_server_ip_;
  }
  if (ret_info_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ret_info_;
  }
  if (this != default_instance_) {
  }
}

void MatchResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google_lalune::protobuf::Descriptor* MatchResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MatchResponse_descriptor_;
}

const MatchResponse& MatchResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

MatchResponse* MatchResponse::default_instance_ = NULL;

MatchResponse* MatchResponse::New() const {
  return new MatchResponse;
}

void MatchResponse::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MatchResponse*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 31) {
    ZR_(game_server_port_, ret_value_);
    if (has_game_uuid()) {
      if (game_uuid_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
        game_uuid_->clear();
      }
    }
    if (has_game_server_ip()) {
      if (game_server_ip_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
        game_server_ip_->clear();
      }
    }
    if (has_ret_info()) {
      if (ret_info_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
        ret_info_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MatchResponse::MergePartialFromCodedStream(
    ::google_lalune::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google_lalune::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:boids.MatchResponse)
  for (;;) {
    ::std::pair< ::google_lalune::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google_lalune::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes game_uuid = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google_lalune::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_game_uuid()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_game_server_ip;
        break;
      }

      // optional string game_server_ip = 3;
      case 3: {
        if (tag == 26) {
         parse_game_server_ip:
          DO_(::google_lalune::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_game_server_ip()));
          ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->game_server_ip().data(), this->game_server_ip().length(),
            ::google_lalune::protobuf::internal::WireFormat::PARSE,
            "game_server_ip");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_game_server_port;
        break;
      }

      // optional uint32 game_server_port = 4;
      case 4: {
        if (tag == 32) {
         parse_game_server_port:
          DO_((::google_lalune::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google_lalune::protobuf::uint32, ::google_lalune::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &game_server_port_)));
          set_has_game_server_port();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_ret_value;
        break;
      }

      // required .boids.MatchResponse.Value ret_value = 5 [default = Success];
      case 5: {
        if (tag == 40) {
         parse_ret_value:
          int value;
          DO_((::google_lalune::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google_lalune::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::boids::MatchResponse_Value_IsValid(value)) {
            set_ret_value(static_cast< ::boids::MatchResponse_Value >(value));
          } else {
            mutable_unknown_fields()->AddVarint(5, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_ret_info;
        break;
      }

      // optional string ret_info = 6;
      case 6: {
        if (tag == 50) {
         parse_ret_info:
          DO_(::google_lalune::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ret_info()));
          ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->ret_info().data(), this->ret_info().length(),
            ::google_lalune::protobuf::internal::WireFormat::PARSE,
            "ret_info");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google_lalune::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google_lalune::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google_lalune::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:boids.MatchResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:boids.MatchResponse)
  return false;
#undef DO_
}

void MatchResponse::SerializeWithCachedSizes(
    ::google_lalune::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:boids.MatchResponse)
  // optional bytes game_uuid = 1;
  if (has_game_uuid()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->game_uuid(), output);
  }

  // optional string game_server_ip = 3;
  if (has_game_server_ip()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->game_server_ip().data(), this->game_server_ip().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "game_server_ip");
    ::google_lalune::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->game_server_ip(), output);
  }

  // optional uint32 game_server_port = 4;
  if (has_game_server_port()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteUInt32(4, this->game_server_port(), output);
  }

  // required .boids.MatchResponse.Value ret_value = 5 [default = Success];
  if (has_ret_value()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->ret_value(), output);
  }

  // optional string ret_info = 6;
  if (has_ret_info()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ret_info().data(), this->ret_info().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "ret_info");
    ::google_lalune::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->ret_info(), output);
  }

  if (!unknown_fields().empty()) {
    ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:boids.MatchResponse)
}

::google_lalune::protobuf::uint8* MatchResponse::SerializeWithCachedSizesToArray(
    ::google_lalune::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:boids.MatchResponse)
  // optional bytes game_uuid = 1;
  if (has_game_uuid()) {
    target =
      ::google_lalune::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->game_uuid(), target);
  }

  // optional string game_server_ip = 3;
  if (has_game_server_ip()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->game_server_ip().data(), this->game_server_ip().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "game_server_ip");
    target =
      ::google_lalune::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->game_server_ip(), target);
  }

  // optional uint32 game_server_port = 4;
  if (has_game_server_port()) {
    target = ::google_lalune::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->game_server_port(), target);
  }

  // required .boids.MatchResponse.Value ret_value = 5 [default = Success];
  if (has_ret_value()) {
    target = ::google_lalune::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->ret_value(), target);
  }

  // optional string ret_info = 6;
  if (has_ret_info()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ret_info().data(), this->ret_info().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "ret_info");
    target =
      ::google_lalune::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->ret_info(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:boids.MatchResponse)
  return target;
}

int MatchResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bytes game_uuid = 1;
    if (has_game_uuid()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::BytesSize(
          this->game_uuid());
    }

    // optional string game_server_ip = 3;
    if (has_game_server_ip()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::StringSize(
          this->game_server_ip());
    }

    // optional uint32 game_server_port = 4;
    if (has_game_server_port()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::UInt32Size(
          this->game_server_port());
    }

    // required .boids.MatchResponse.Value ret_value = 5 [default = Success];
    if (has_ret_value()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::EnumSize(this->ret_value());
    }

    // optional string ret_info = 6;
    if (has_ret_info()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::StringSize(
          this->ret_info());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google_lalune::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MatchResponse::MergeFrom(const ::google_lalune::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MatchResponse* source =
    ::google_lalune::protobuf::internal::dynamic_cast_if_available<const MatchResponse*>(
      &from);
  if (source == NULL) {
    ::google_lalune::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MatchResponse::MergeFrom(const MatchResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_game_uuid()) {
      set_game_uuid(from.game_uuid());
    }
    if (from.has_game_server_ip()) {
      set_game_server_ip(from.game_server_ip());
    }
    if (from.has_game_server_port()) {
      set_game_server_port(from.game_server_port());
    }
    if (from.has_ret_value()) {
      set_ret_value(from.ret_value());
    }
    if (from.has_ret_info()) {
      set_ret_info(from.ret_info());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MatchResponse::CopyFrom(const ::google_lalune::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MatchResponse::CopyFrom(const MatchResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MatchResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000008) != 0x00000008) return false;

  return true;
}

void MatchResponse::Swap(MatchResponse* other) {
  if (other != this) {
    std::swap(game_uuid_, other->game_uuid_);
    std::swap(game_server_ip_, other->game_server_ip_);
    std::swap(game_server_port_, other->game_server_port_);
    std::swap(ret_value_, other->ret_value_);
    std::swap(ret_info_, other->ret_info_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google_lalune::protobuf::Metadata MatchResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google_lalune::protobuf::Metadata metadata;
  metadata.descriptor = MatchResponse_descriptor_;
  metadata.reflection = MatchResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CreateGame::kGameIdFieldNumber;
const int CreateGame::kGameInitDataFieldNumber;
#endif  // !_MSC_VER

CreateGame::CreateGame()
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:boids.CreateGame)
}

void CreateGame::InitAsDefaultInstance() {
  game_init_data_ = const_cast< ::boids::GameInitData*>(&::boids::GameInitData::default_instance());
}

CreateGame::CreateGame(const CreateGame& from)
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:boids.CreateGame)
}

void CreateGame::SharedCtor() {
  ::google_lalune::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  game_id_ = const_cast< ::std::string*>(&::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited());
  game_init_data_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CreateGame::~CreateGame() {
  // @@protoc_insertion_point(destructor:boids.CreateGame)
  SharedDtor();
}

void CreateGame::SharedDtor() {
  if (game_id_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete game_id_;
  }
  if (this != default_instance_) {
    delete game_init_data_;
  }
}

void CreateGame::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google_lalune::protobuf::Descriptor* CreateGame::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CreateGame_descriptor_;
}

const CreateGame& CreateGame::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

CreateGame* CreateGame::default_instance_ = NULL;

CreateGame* CreateGame::New() const {
  return new CreateGame;
}

void CreateGame::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_game_id()) {
      if (game_id_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
        game_id_->clear();
      }
    }
    if (has_game_init_data()) {
      if (game_init_data_ != NULL) game_init_data_->::boids::GameInitData::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CreateGame::MergePartialFromCodedStream(
    ::google_lalune::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google_lalune::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:boids.CreateGame)
  for (;;) {
    ::std::pair< ::google_lalune::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google_lalune::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes game_id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google_lalune::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_game_id()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_game_init_data;
        break;
      }

      // required .boids.GameInitData game_init_data = 2;
      case 2: {
        if (tag == 18) {
         parse_game_init_data:
          DO_(::google_lalune::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_game_init_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google_lalune::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google_lalune::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google_lalune::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:boids.CreateGame)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:boids.CreateGame)
  return false;
#undef DO_
}

void CreateGame::SerializeWithCachedSizes(
    ::google_lalune::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:boids.CreateGame)
  // required bytes game_id = 1;
  if (has_game_id()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->game_id(), output);
  }

  // required .boids.GameInitData game_init_data = 2;
  if (has_game_init_data()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->game_init_data(), output);
  }

  if (!unknown_fields().empty()) {
    ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:boids.CreateGame)
}

::google_lalune::protobuf::uint8* CreateGame::SerializeWithCachedSizesToArray(
    ::google_lalune::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:boids.CreateGame)
  // required bytes game_id = 1;
  if (has_game_id()) {
    target =
      ::google_lalune::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->game_id(), target);
  }

  // required .boids.GameInitData game_init_data = 2;
  if (has_game_init_data()) {
    target = ::google_lalune::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->game_init_data(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:boids.CreateGame)
  return target;
}

int CreateGame::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes game_id = 1;
    if (has_game_id()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::BytesSize(
          this->game_id());
    }

    // required .boids.GameInitData game_init_data = 2;
    if (has_game_init_data()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->game_init_data());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google_lalune::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CreateGame::MergeFrom(const ::google_lalune::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CreateGame* source =
    ::google_lalune::protobuf::internal::dynamic_cast_if_available<const CreateGame*>(
      &from);
  if (source == NULL) {
    ::google_lalune::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CreateGame::MergeFrom(const CreateGame& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_game_id()) {
      set_game_id(from.game_id());
    }
    if (from.has_game_init_data()) {
      mutable_game_init_data()->::boids::GameInitData::MergeFrom(from.game_init_data());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CreateGame::CopyFrom(const ::google_lalune::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CreateGame::CopyFrom(const CreateGame& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateGame::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_game_init_data()) {
    if (!this->game_init_data().IsInitialized()) return false;
  }
  return true;
}

void CreateGame::Swap(CreateGame* other) {
  if (other != this) {
    std::swap(game_id_, other->game_id_);
    std::swap(game_init_data_, other->game_init_data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google_lalune::protobuf::Metadata CreateGame::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google_lalune::protobuf::Metadata metadata;
  metadata.descriptor = CreateGame_descriptor_;
  metadata.reflection = CreateGame_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CreateGameResponse::kGameIdFieldNumber;
const int CreateGameResponse::kRetValueFieldNumber;
#endif  // !_MSC_VER

CreateGameResponse::CreateGameResponse()
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:boids.CreateGameResponse)
}

void CreateGameResponse::InitAsDefaultInstance() {
}

CreateGameResponse::CreateGameResponse(const CreateGameResponse& from)
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:boids.CreateGameResponse)
}

void CreateGameResponse::SharedCtor() {
  ::google_lalune::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  game_id_ = const_cast< ::std::string*>(&::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited());
  ret_value_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CreateGameResponse::~CreateGameResponse() {
  // @@protoc_insertion_point(destructor:boids.CreateGameResponse)
  SharedDtor();
}

void CreateGameResponse::SharedDtor() {
  if (game_id_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete game_id_;
  }
  if (this != default_instance_) {
  }
}

void CreateGameResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google_lalune::protobuf::Descriptor* CreateGameResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CreateGameResponse_descriptor_;
}

const CreateGameResponse& CreateGameResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

CreateGameResponse* CreateGameResponse::default_instance_ = NULL;

CreateGameResponse* CreateGameResponse::New() const {
  return new CreateGameResponse;
}

void CreateGameResponse::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_game_id()) {
      if (game_id_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
        game_id_->clear();
      }
    }
    ret_value_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CreateGameResponse::MergePartialFromCodedStream(
    ::google_lalune::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google_lalune::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:boids.CreateGameResponse)
  for (;;) {
    ::std::pair< ::google_lalune::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google_lalune::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes game_id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google_lalune::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_game_id()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_ret_value;
        break;
      }

      // required int32 ret_value = 2;
      case 2: {
        if (tag == 16) {
         parse_ret_value:
          DO_((::google_lalune::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google_lalune::protobuf::int32, ::google_lalune::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ret_value_)));
          set_has_ret_value();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google_lalune::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google_lalune::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google_lalune::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:boids.CreateGameResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:boids.CreateGameResponse)
  return false;
#undef DO_
}

void CreateGameResponse::SerializeWithCachedSizes(
    ::google_lalune::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:boids.CreateGameResponse)
  // required bytes game_id = 1;
  if (has_game_id()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->game_id(), output);
  }

  // required int32 ret_value = 2;
  if (has_ret_value()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteInt32(2, this->ret_value(), output);
  }

  if (!unknown_fields().empty()) {
    ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:boids.CreateGameResponse)
}

::google_lalune::protobuf::uint8* CreateGameResponse::SerializeWithCachedSizesToArray(
    ::google_lalune::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:boids.CreateGameResponse)
  // required bytes game_id = 1;
  if (has_game_id()) {
    target =
      ::google_lalune::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->game_id(), target);
  }

  // required int32 ret_value = 2;
  if (has_ret_value()) {
    target = ::google_lalune::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->ret_value(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:boids.CreateGameResponse)
  return target;
}

int CreateGameResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes game_id = 1;
    if (has_game_id()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::BytesSize(
          this->game_id());
    }

    // required int32 ret_value = 2;
    if (has_ret_value()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::Int32Size(
          this->ret_value());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google_lalune::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CreateGameResponse::MergeFrom(const ::google_lalune::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CreateGameResponse* source =
    ::google_lalune::protobuf::internal::dynamic_cast_if_available<const CreateGameResponse*>(
      &from);
  if (source == NULL) {
    ::google_lalune::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CreateGameResponse::MergeFrom(const CreateGameResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_game_id()) {
      set_game_id(from.game_id());
    }
    if (from.has_ret_value()) {
      set_ret_value(from.ret_value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CreateGameResponse::CopyFrom(const ::google_lalune::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CreateGameResponse::CopyFrom(const CreateGameResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateGameResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void CreateGameResponse::Swap(CreateGameResponse* other) {
  if (other != this) {
    std::swap(game_id_, other->game_id_);
    std::swap(ret_value_, other->ret_value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google_lalune::protobuf::Metadata CreateGameResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google_lalune::protobuf::Metadata metadata;
  metadata.descriptor = CreateGameResponse_descriptor_;
  metadata.reflection = CreateGameResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PvPServerRegister::kIpFieldNumber;
const int PvPServerRegister::kPortFieldNumber;
const int PvPServerRegister::kRegionFieldNumber;
const int PvPServerRegister::kPriorityFieldNumber;
#endif  // !_MSC_VER

PvPServerRegister::PvPServerRegister()
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:boids.PvPServerRegister)
}

void PvPServerRegister::InitAsDefaultInstance() {
}

PvPServerRegister::PvPServerRegister(const PvPServerRegister& from)
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:boids.PvPServerRegister)
}

void PvPServerRegister::SharedCtor() {
  ::google_lalune::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  ip_ = const_cast< ::std::string*>(&::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited());
  port_ = 0u;
  region_ = 0;
  priority_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PvPServerRegister::~PvPServerRegister() {
  // @@protoc_insertion_point(destructor:boids.PvPServerRegister)
  SharedDtor();
}

void PvPServerRegister::SharedDtor() {
  if (ip_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ip_;
  }
  if (this != default_instance_) {
  }
}

void PvPServerRegister::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google_lalune::protobuf::Descriptor* PvPServerRegister::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PvPServerRegister_descriptor_;
}

const PvPServerRegister& PvPServerRegister::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

PvPServerRegister* PvPServerRegister::default_instance_ = NULL;

PvPServerRegister* PvPServerRegister::New() const {
  return new PvPServerRegister;
}

void PvPServerRegister::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<PvPServerRegister*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 15) {
    ZR_(port_, priority_);
    if (has_ip()) {
      if (ip_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
        ip_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PvPServerRegister::MergePartialFromCodedStream(
    ::google_lalune::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google_lalune::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:boids.PvPServerRegister)
  for (;;) {
    ::std::pair< ::google_lalune::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google_lalune::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string ip = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google_lalune::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ip()));
          ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->ip().data(), this->ip().length(),
            ::google_lalune::protobuf::internal::WireFormat::PARSE,
            "ip");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_port;
        break;
      }

      // required uint32 port = 2;
      case 2: {
        if (tag == 16) {
         parse_port:
          DO_((::google_lalune::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google_lalune::protobuf::uint32, ::google_lalune::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &port_)));
          set_has_port();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_region;
        break;
      }

      // optional int32 region = 3;
      case 3: {
        if (tag == 24) {
         parse_region:
          DO_((::google_lalune::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google_lalune::protobuf::int32, ::google_lalune::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &region_)));
          set_has_region();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_priority;
        break;
      }

      // optional int32 priority = 4;
      case 4: {
        if (tag == 32) {
         parse_priority:
          DO_((::google_lalune::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google_lalune::protobuf::int32, ::google_lalune::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &priority_)));
          set_has_priority();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google_lalune::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google_lalune::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google_lalune::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:boids.PvPServerRegister)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:boids.PvPServerRegister)
  return false;
#undef DO_
}

void PvPServerRegister::SerializeWithCachedSizes(
    ::google_lalune::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:boids.PvPServerRegister)
  // required string ip = 1;
  if (has_ip()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ip().data(), this->ip().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "ip");
    ::google_lalune::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->ip(), output);
  }

  // required uint32 port = 2;
  if (has_port()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteUInt32(2, this->port(), output);
  }

  // optional int32 region = 3;
  if (has_region()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteInt32(3, this->region(), output);
  }

  // optional int32 priority = 4;
  if (has_priority()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteInt32(4, this->priority(), output);
  }

  if (!unknown_fields().empty()) {
    ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:boids.PvPServerRegister)
}

::google_lalune::protobuf::uint8* PvPServerRegister::SerializeWithCachedSizesToArray(
    ::google_lalune::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:boids.PvPServerRegister)
  // required string ip = 1;
  if (has_ip()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ip().data(), this->ip().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "ip");
    target =
      ::google_lalune::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ip(), target);
  }

  // required uint32 port = 2;
  if (has_port()) {
    target = ::google_lalune::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->port(), target);
  }

  // optional int32 region = 3;
  if (has_region()) {
    target = ::google_lalune::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->region(), target);
  }

  // optional int32 priority = 4;
  if (has_priority()) {
    target = ::google_lalune::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->priority(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:boids.PvPServerRegister)
  return target;
}

int PvPServerRegister::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string ip = 1;
    if (has_ip()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::StringSize(
          this->ip());
    }

    // required uint32 port = 2;
    if (has_port()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::UInt32Size(
          this->port());
    }

    // optional int32 region = 3;
    if (has_region()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::Int32Size(
          this->region());
    }

    // optional int32 priority = 4;
    if (has_priority()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::Int32Size(
          this->priority());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google_lalune::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PvPServerRegister::MergeFrom(const ::google_lalune::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PvPServerRegister* source =
    ::google_lalune::protobuf::internal::dynamic_cast_if_available<const PvPServerRegister*>(
      &from);
  if (source == NULL) {
    ::google_lalune::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PvPServerRegister::MergeFrom(const PvPServerRegister& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_ip()) {
      set_ip(from.ip());
    }
    if (from.has_port()) {
      set_port(from.port());
    }
    if (from.has_region()) {
      set_region(from.region());
    }
    if (from.has_priority()) {
      set_priority(from.priority());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PvPServerRegister::CopyFrom(const ::google_lalune::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PvPServerRegister::CopyFrom(const PvPServerRegister& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PvPServerRegister::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void PvPServerRegister::Swap(PvPServerRegister* other) {
  if (other != this) {
    std::swap(ip_, other->ip_);
    std::swap(port_, other->port_);
    std::swap(region_, other->region_);
    std::swap(priority_, other->priority_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google_lalune::protobuf::Metadata PvPServerRegister::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google_lalune::protobuf::Metadata metadata;
  metadata.descriptor = PvPServerRegister_descriptor_;
  metadata.reflection = PvPServerRegister_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PvPServerRegisterResponse::kRetValueFieldNumber;
#endif  // !_MSC_VER

PvPServerRegisterResponse::PvPServerRegisterResponse()
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:boids.PvPServerRegisterResponse)
}

void PvPServerRegisterResponse::InitAsDefaultInstance() {
}

PvPServerRegisterResponse::PvPServerRegisterResponse(const PvPServerRegisterResponse& from)
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:boids.PvPServerRegisterResponse)
}

void PvPServerRegisterResponse::SharedCtor() {
  _cached_size_ = 0;
  ret_value_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PvPServerRegisterResponse::~PvPServerRegisterResponse() {
  // @@protoc_insertion_point(destructor:boids.PvPServerRegisterResponse)
  SharedDtor();
}

void PvPServerRegisterResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PvPServerRegisterResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google_lalune::protobuf::Descriptor* PvPServerRegisterResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PvPServerRegisterResponse_descriptor_;
}

const PvPServerRegisterResponse& PvPServerRegisterResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

PvPServerRegisterResponse* PvPServerRegisterResponse::default_instance_ = NULL;

PvPServerRegisterResponse* PvPServerRegisterResponse::New() const {
  return new PvPServerRegisterResponse;
}

void PvPServerRegisterResponse::Clear() {
  ret_value_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PvPServerRegisterResponse::MergePartialFromCodedStream(
    ::google_lalune::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google_lalune::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:boids.PvPServerRegisterResponse)
  for (;;) {
    ::std::pair< ::google_lalune::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google_lalune::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 ret_value = 1 [default = 0];
      case 1: {
        if (tag == 8) {
          DO_((::google_lalune::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google_lalune::protobuf::int32, ::google_lalune::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ret_value_)));
          set_has_ret_value();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google_lalune::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google_lalune::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google_lalune::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:boids.PvPServerRegisterResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:boids.PvPServerRegisterResponse)
  return false;
#undef DO_
}

void PvPServerRegisterResponse::SerializeWithCachedSizes(
    ::google_lalune::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:boids.PvPServerRegisterResponse)
  // required int32 ret_value = 1 [default = 0];
  if (has_ret_value()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteInt32(1, this->ret_value(), output);
  }

  if (!unknown_fields().empty()) {
    ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:boids.PvPServerRegisterResponse)
}

::google_lalune::protobuf::uint8* PvPServerRegisterResponse::SerializeWithCachedSizesToArray(
    ::google_lalune::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:boids.PvPServerRegisterResponse)
  // required int32 ret_value = 1 [default = 0];
  if (has_ret_value()) {
    target = ::google_lalune::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->ret_value(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:boids.PvPServerRegisterResponse)
  return target;
}

int PvPServerRegisterResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 ret_value = 1 [default = 0];
    if (has_ret_value()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::Int32Size(
          this->ret_value());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google_lalune::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PvPServerRegisterResponse::MergeFrom(const ::google_lalune::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PvPServerRegisterResponse* source =
    ::google_lalune::protobuf::internal::dynamic_cast_if_available<const PvPServerRegisterResponse*>(
      &from);
  if (source == NULL) {
    ::google_lalune::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PvPServerRegisterResponse::MergeFrom(const PvPServerRegisterResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_ret_value()) {
      set_ret_value(from.ret_value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PvPServerRegisterResponse::CopyFrom(const ::google_lalune::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PvPServerRegisterResponse::CopyFrom(const PvPServerRegisterResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PvPServerRegisterResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void PvPServerRegisterResponse::Swap(PvPServerRegisterResponse* other) {
  if (other != this) {
    std::swap(ret_value_, other->ret_value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google_lalune::protobuf::Metadata PvPServerRegisterResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google_lalune::protobuf::Metadata metadata;
  metadata.descriptor = PvPServerRegisterResponse_descriptor_;
  metadata.reflection = PvPServerRegisterResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PvPServerHeartBeat::kIpFieldNumber;
const int PvPServerHeartBeat::kPortFieldNumber;
#endif  // !_MSC_VER

PvPServerHeartBeat::PvPServerHeartBeat()
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:boids.PvPServerHeartBeat)
}

void PvPServerHeartBeat::InitAsDefaultInstance() {
}

PvPServerHeartBeat::PvPServerHeartBeat(const PvPServerHeartBeat& from)
  : ::google_lalune::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:boids.PvPServerHeartBeat)
}

void PvPServerHeartBeat::SharedCtor() {
  ::google_lalune::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  ip_ = const_cast< ::std::string*>(&::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited());
  port_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PvPServerHeartBeat::~PvPServerHeartBeat() {
  // @@protoc_insertion_point(destructor:boids.PvPServerHeartBeat)
  SharedDtor();
}

void PvPServerHeartBeat::SharedDtor() {
  if (ip_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ip_;
  }
  if (this != default_instance_) {
  }
}

void PvPServerHeartBeat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google_lalune::protobuf::Descriptor* PvPServerHeartBeat::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PvPServerHeartBeat_descriptor_;
}

const PvPServerHeartBeat& PvPServerHeartBeat::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

PvPServerHeartBeat* PvPServerHeartBeat::default_instance_ = NULL;

PvPServerHeartBeat* PvPServerHeartBeat::New() const {
  return new PvPServerHeartBeat;
}

void PvPServerHeartBeat::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_ip()) {
      if (ip_ != &::google_lalune::protobuf::internal::GetEmptyStringAlreadyInited()) {
        ip_->clear();
      }
    }
    port_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PvPServerHeartBeat::MergePartialFromCodedStream(
    ::google_lalune::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google_lalune::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:boids.PvPServerHeartBeat)
  for (;;) {
    ::std::pair< ::google_lalune::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google_lalune::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string ip = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google_lalune::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ip()));
          ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->ip().data(), this->ip().length(),
            ::google_lalune::protobuf::internal::WireFormat::PARSE,
            "ip");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_port;
        break;
      }

      // required uint32 port = 2;
      case 2: {
        if (tag == 16) {
         parse_port:
          DO_((::google_lalune::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google_lalune::protobuf::uint32, ::google_lalune::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &port_)));
          set_has_port();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google_lalune::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google_lalune::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google_lalune::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:boids.PvPServerHeartBeat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:boids.PvPServerHeartBeat)
  return false;
#undef DO_
}

void PvPServerHeartBeat::SerializeWithCachedSizes(
    ::google_lalune::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:boids.PvPServerHeartBeat)
  // required string ip = 1;
  if (has_ip()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ip().data(), this->ip().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "ip");
    ::google_lalune::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->ip(), output);
  }

  // required uint32 port = 2;
  if (has_port()) {
    ::google_lalune::protobuf::internal::WireFormatLite::WriteUInt32(2, this->port(), output);
  }

  if (!unknown_fields().empty()) {
    ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:boids.PvPServerHeartBeat)
}

::google_lalune::protobuf::uint8* PvPServerHeartBeat::SerializeWithCachedSizesToArray(
    ::google_lalune::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:boids.PvPServerHeartBeat)
  // required string ip = 1;
  if (has_ip()) {
    ::google_lalune::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ip().data(), this->ip().length(),
      ::google_lalune::protobuf::internal::WireFormat::SERIALIZE,
      "ip");
    target =
      ::google_lalune::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ip(), target);
  }

  // required uint32 port = 2;
  if (has_port()) {
    target = ::google_lalune::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->port(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google_lalune::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:boids.PvPServerHeartBeat)
  return target;
}

int PvPServerHeartBeat::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string ip = 1;
    if (has_ip()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::StringSize(
          this->ip());
    }

    // required uint32 port = 2;
    if (has_port()) {
      total_size += 1 +
        ::google_lalune::protobuf::internal::WireFormatLite::UInt32Size(
          this->port());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google_lalune::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PvPServerHeartBeat::MergeFrom(const ::google_lalune::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PvPServerHeartBeat* source =
    ::google_lalune::protobuf::internal::dynamic_cast_if_available<const PvPServerHeartBeat*>(
      &from);
  if (source == NULL) {
    ::google_lalune::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PvPServerHeartBeat::MergeFrom(const PvPServerHeartBeat& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_ip()) {
      set_ip(from.ip());
    }
    if (from.has_port()) {
      set_port(from.port());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PvPServerHeartBeat::CopyFrom(const ::google_lalune::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PvPServerHeartBeat::CopyFrom(const PvPServerHeartBeat& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PvPServerHeartBeat::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void PvPServerHeartBeat::Swap(PvPServerHeartBeat* other) {
  if (other != this) {
    std::swap(ip_, other->ip_);
    std::swap(port_, other->port_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google_lalune::protobuf::Metadata PvPServerHeartBeat::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google_lalune::protobuf::Metadata metadata;
  metadata.descriptor = PvPServerHeartBeat_descriptor_;
  metadata.reflection = PvPServerHeartBeat_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace boids

// @@protoc_insertion_point(global_scope)
